debug: false

spring:
  resources:
    static-locations: classpath:static/,file:E://temp-rainy/  #设置静态资源路径
  datasource:
    url: jdbc:mysql://localhost:3306/sale_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


  servlet:
    multipart:
      enabled: true #是否启用文件上传功能
      file-size-threshold: 0  #指定文件写入磁盘后的阈值，默认为0
      location: D:/springboot/upload  #指定文件的位置, 没有指定时会自动创建一个临时文件夹
      max-file-size: 10MB  #指定上传文件大小， 默认1M
      max-request-size: 50MB  #指定multipart / form-data请求允许的最大大小， 默认10M
      resolve-lazily: false  #是否在文件或参数访问时懒惰地解析多部分请求

  #设置前缀和后缀
  thymeleaf:
    cache: false  #缓存
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/


mybatis:
  mapper-locations: classpath:mapper/*.xml    #设置xml路径
